name: MEMKIND
on: [push, pull_request]

jobs:

  rpm-build-fedora:
    runs-on: ubuntu-20.04
    name: RPM build
    env:
      UTIL_PREFIX: utils/docker
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run in LXC (Fedora 33)
        uses: wsdfhjxc/run-in-lxc-action@1.x
        with:
          distr: fedora
          release: 33
          run: |
            sudo dnf -y install automake daxctl-devel git g++ libtool numactl-devel rpmdevtools
            env.UTIL_PREFIX/docker_install_hwloc.sh env.UTIL_PREFIX
            ./autogen.sh
            ./configure
            make rpm
